name: Deploy to Target VM

on:
  push:
    branches:
      - Lab3
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Application via Compose
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Copy files and deploy
        run: |
          echo "1. Creating a folder..."
          ssh -o StrictHostKeyChecking=no miracle@192.168.1.120 "mkdir -p ~/devOps-project"

          echo "2. Transporting files to Target VM..."
          scp -o StrictHostKeyChecking=no -r ./* miracle@192.168.1.120:~/devOps-project/

          echo "3. Installing Docker and Docker Compose..."
          ssh -o StrictHostKeyChecking=no miracle@192.168.1.120 << 'EOF'
            echo "installation..."
            sudo apt-get update
            sudo apt-get install -y docker.io docker-compose-v2

            cd ~/devOps-project/

            echo "Closing previous containers..."
            sudo docker compose down
            sudo docker compose up -d --build

            echo "Deployment completed successfully"
          EOF

      - name: Verify Deployment
        run: |
          echo "Waiting for containers to start..."
          sleep 30

          echo "Checking the server availability..."
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://192.168.1.120:8080)

          if [ "$HTTP_STATUS" -ne 200 ]; then
            echo "Error: Returned HTTP $HTTP_STATUS instead of 200"
            exit 1
          fi
          echo "Service is available"

          echo "Checking the Nginx configuration..."
          SERVER_HEADER=$(curl -s -I http://192.168.1.120:8080 | grep -i "^Server:")

          if [[ "$SERVER_HEADER" != *"nginx"* ]]; then
            echo "Error: Server header does not contain 'nginx'."
            exit 1
          fi
          echo "Nginx is running and configured correctly."

          echo "Verification completed!"

